import { StyleProp, TextStyle } from 'react-native'

export const scrollArea: StyleProp<TextStyle>
export const detail: StyleProp<TextStyle>
export const no-scroll: StyleProp<TextStyle>
export const searcPage: StyleProp<TextStyle>
export const vue-fixed-header--isFixed: StyleProp<TextStyle>
export const sectionTitle: StyleProp<TextStyle>
export const iconBorder: StyleProp<TextStyle>
export const overlay: StyleProp<TextStyle>
export const mainBanner: StyleProp<TextStyle>
export const carousel: StyleProp<TextStyle>
export const carousel-inner: StyleProp<TextStyle>
export const sr-only: StyleProp<TextStyle>
export const nav-tabs: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const swiper-slide: StyleProp<TextStyle>
export const tabs: StyleProp<TextStyle>
export const nav-pills: StyleProp<TextStyle>
export const scrollbar-thumb: StyleProp<TextStyle>
export const scrollbar-track-y: StyleProp<TextStyle>
export const v-select: StyleProp<TextStyle>
export const arrow-down: StyleProp<TextStyle>
export const v-dropdown-container: StyleProp<TextStyle>
export const selected: StyleProp<TextStyle>
export const home: StyleProp<TextStyle>
export const financialReports: StyleProp<TextStyle>
export const modal-open: StyleProp<TextStyle>
export const d-none-767: StyleProp<TextStyle>
export const d-show-767: StyleProp<TextStyle>
export const iconTabs: StyleProp<TextStyle>
export const tab-icon: StyleProp<TextStyle>
export const tableWrapperon-991: StyleProp<TextStyle>
export const tableWrapperon-767: StyleProp<TextStyle>
export const tableWrapperon-575: StyleProp<TextStyle>
export const baseSearchlist: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const media-image: StyleProp<TextStyle>
export const mediaVideo: StyleProp<TextStyle>
export const baseSearchlist__card--mediaslider: StyleProp<TextStyle>
export const sliderPills: StyleProp<TextStyle>
export const sliderPills__item: StyleProp<TextStyle>
export const countrySlides: StyleProp<TextStyle>
export const country: StyleProp<TextStyle>
export const insetItem: StyleProp<TextStyle>
export const content-scroll: StyleProp<TextStyle>
export const inner-scroll: StyleProp<TextStyle>
export const nice-bar-slider-x: StyleProp<TextStyle>
export const nice-bar-rail-y: StyleProp<TextStyle>
export const nice-bar-slider-y: StyleProp<TextStyle>
export const contentWrapper: StyleProp<TextStyle>
export const container: StyleProp<TextStyle>
export const vs__dropdown-toggle: StyleProp<TextStyle>
export const vs__selected: StyleProp<TextStyle>
export const vs__dropdown-option: StyleProp<TextStyle>
export const vs__dropdown-option--highlight: StyleProp<TextStyle>
export const vs__actions: StyleProp<TextStyle>
export const vs__open-indicator: StyleProp<TextStyle>
