import { StyleProp, TextStyle } from 'react-native'

export const container: StyleProp<TextStyle>
export const sectionTitle: StyleProp<TextStyle>
export const slider-services: StyleProp<TextStyle>
export const swiper-slide: StyleProp<TextStyle>
export const swiper-slide-active: StyleProp<TextStyle>
export const slider-item: StyleProp<TextStyle>
export const custom-btn: StyleProp<TextStyle>
export const header-div: StyleProp<TextStyle>
export const 98px): StyleProp<TextStyle>
export const bg-opaciy: StyleProp<TextStyle>
export const header-slider: StyleProp<TextStyle>
export const heaer-slider-item: StyleProp<TextStyle>
export const slider-search: StyleProp<TextStyle>
export const search-icon: StyleProp<TextStyle>
export const vue-typer: StyleProp<TextStyle>
export const 8px): StyleProp<TextStyle>
export const watch-video: StyleProp<TextStyle>
export const animate-video: StyleProp<TextStyle>
export const container-right: StyleProp<TextStyle>
export const content-scroll: StyleProp<TextStyle>
export const inner-scroll: StyleProp<TextStyle>
export const nice-bar-slider-x: StyleProp<TextStyle>
export const nice-bar-rail-y: StyleProp<TextStyle>
export const nice-bar-slider-y: StyleProp<TextStyle>
export const v-select: StyleProp<TextStyle>
export const vs__dropdown-toggle: StyleProp<TextStyle>
export const vs__selected: StyleProp<TextStyle>
export const vs__dropdown-option: StyleProp<TextStyle>
export const vs__dropdown-option--highlight: StyleProp<TextStyle>
export const vs__actions: StyleProp<TextStyle>
export const vs__open-indicator: StyleProp<TextStyle>
export const pagination: StyleProp<TextStyle>
export const page-item: StyleProp<TextStyle>
export const page-link: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const vs__clear: StyleProp<TextStyle>
export const tabs: StyleProp<TextStyle>
export const nav-pills: StyleProp<TextStyle>
export const nav-link: StyleProp<TextStyle>
export const scrollArea: StyleProp<TextStyle>
export const scrollbar-content: StyleProp<TextStyle>
export const scrollbar: StyleProp<TextStyle>
export const scrollbar-y: StyleProp<TextStyle>
export const __vuescroll: StyleProp<TextStyle>
export const __rail-is-vertical: StyleProp<TextStyle>
export const __bar-is-vertical: StyleProp<TextStyle>
export const __bar-wrap-is-vertical: StyleProp<TextStyle>
export const detail: StyleProp<TextStyle>
export const no-scroll: StyleProp<TextStyle>
export const content-box: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const slide__card: StyleProp<TextStyle>
export const slide__card--image: StyleProp<TextStyle>
export const iconTabs: StyleProp<TextStyle>
export const tab-icon: StyleProp<TextStyle>
export const selected: StyleProp<TextStyle>
export const scrollbar-wrap: StyleProp<TextStyle>
