import { StyleProp, TextStyle } from 'react-native'

export const mb-#$item}: StyleProp<TextStyle>
export const mt-#$item}: StyleProp<TextStyle>
export const pb-#$item}: StyleProp<TextStyle>
export const pt-#$item}: StyleProp<TextStyle>
export const col-gap-#$item}: StyleProp<TextStyle>
export const col-gap-#$item}>div: StyleProp<TextStyle>
export const grid: StyleProp<TextStyle>
export const card: StyleProp<TextStyle>
export const card-body: StyleProp<TextStyle>
export const desc: StyleProp<TextStyle>
export const dropzone: StyleProp<TextStyle>
export const dz-message: StyleProp<TextStyle>
export const dz-button: StyleProp<TextStyle>
export const note: StyleProp<TextStyle>
export const dz-preview: StyleProp<TextStyle>
export const dz-image: StyleProp<TextStyle>
export const mb-35: StyleProp<TextStyle>
export const mt-15: StyleProp<TextStyle>
export const accordion: StyleProp<TextStyle>
export const card__header: StyleProp<TextStyle>
export const collapsed: StyleProp<TextStyle>
export const abs-link: StyleProp<TextStyle>
export const table: StyleProp<TextStyle>
export const new: StyleProp<TextStyle>
export const Feedback: StyleProp<TextStyle>
export const In-progress: StyleProp<TextStyle>
export const sm: StyleProp<TextStyle>
export const action-btns: StyleProp<TextStyle>
export const download: StyleProp<TextStyle>
export const table__row--cell: StyleProp<TextStyle>
export const green: StyleProp<TextStyle>
export const blue: StyleProp<TextStyle>
export const orange: StyleProp<TextStyle>
export const dropdown: StyleProp<TextStyle>
export const btn-secondary: StyleProp<TextStyle>
export const dropdown-toggle: StyleProp<TextStyle>
export const b-0: StyleProp<TextStyle>
export const nav__tabs: StyleProp<TextStyle>
export const active: StyleProp<TextStyle>
export const img-lazyloader: StyleProp<TextStyle>
export const image-hover: StyleProp<TextStyle>
export const detail-list: StyleProp<TextStyle>
export const two-columns: StyleProp<TextStyle>
export const icon: StyleProp<TextStyle>
export const area: StyleProp<TextStyle>
export const front-page: StyleProp<TextStyle>
export const progress-container: StyleProp<TextStyle>
export const progress-bar: StyleProp<TextStyle>
export const checkbox--switch: StyleProp<TextStyle>
export const custom__tooltip: StyleProp<TextStyle>
export const custom__tooltip--content: StyleProp<TextStyle>
export const mCSB_scrollTools: StyleProp<TextStyle>
export const mCSB_dragger: StyleProp<TextStyle>
export const mCSB_dragger_bar: StyleProp<TextStyle>
export const mCSB_draggerRail: StyleProp<TextStyle>
export const mCSB_draggerContainer: StyleProp<TextStyle>
export const screen__images: StyleProp<TextStyle>
export const delete: StyleProp<TextStyle>
export const bootstrap-datetimepicker-widget: StyleProp<TextStyle>
export const row: StyleProp<TextStyle>
export const col-md-6: StyleProp<TextStyle>
export const timepicker: StyleProp<TextStyle>
export const prev: StyleProp<TextStyle>
export const picker-switch: StyleProp<TextStyle>
export const day: StyleProp<TextStyle>
export const datepicker: StyleProp<TextStyle>
export const activedisabled: StyleProp<TextStyle>
export const activedisabled:hover: StyleProp<TextStyle>
export const next: StyleProp<TextStyle>
export const loadmore: StyleProp<TextStyle>
export const show: StyleProp<TextStyle>
export const animate: StyleProp<TextStyle>
export const slideIn: StyleProp<TextStyle>
export const v-dropdown-item[data-v-138dff1d]: StyleProp<TextStyle>
export const default-option): StyleProp<TextStyle>
export const selected: StyleProp<TextStyle>
export const v-dropdown-container[data-v-138dff1d]: StyleProp<TextStyle>
export const v-select-toggle[data-v-138dff1d]: StyleProp<TextStyle>
export const arrow-down: StyleProp<TextStyle>
export const dropdown-menu: StyleProp<TextStyle>
export const dropdown-item: StyleProp<TextStyle>
export const feedback: StyleProp<TextStyle>
export const in-progress: StyleProp<TextStyle>
export const compeleted: StyleProp<TextStyle>
export const btn: StyleProp<TextStyle>
export const b-form-btn-label-controlform-control>label: StyleProp<TextStyle>
export const __vuescroll: StyleProp<TextStyle>
export const __rail-is-vertical: StyleProp<TextStyle>
export const __bar-is-vertical: StyleProp<TextStyle>
export const img-hover: StyleProp<TextStyle>
export const vdp-datepicker: StyleProp<TextStyle>
export const form-control: StyleProp<TextStyle>
export const input-group-append: StyleProp<TextStyle>
export const input-group-text: StyleProp<TextStyle>
export const cell: StyleProp<TextStyle>
export const blank):not(disabled)year:hover: StyleProp<TextStyle>
export const up:not(disabled):hover: StyleProp<TextStyle>
export const ar: StyleProp<TextStyle>
export const v-dropdown-item: StyleProp<TextStyle>
export const vdp-datepicker:after: StyleProp<TextStyle>
export const dropdown-toggle:after: StyleProp<TextStyle>
export const __panel: StyleProp<TextStyle>
export const modal: StyleProp<TextStyle>
export const modal-dialog: StyleProp<TextStyle>
export const modal-content: StyleProp<TextStyle>
export const popup-cross-icon: StyleProp<TextStyle>
export const modal-header: StyleProp<TextStyle>
export const close: StyleProp<TextStyle>
